spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?sslmode=require}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  mail:
    from: ${MAIL_FROM:}
    admin: ${MAIL_ADMIN:}
    sender-name: ${MAIL_SENDER_NAME:Sri Vaari}
    brevo:
      api-key: ${BREVO_API_KEY:}

logging:
  level:
    com.motors: DEBUG
    org.hibernate.SQL: DEBUG
