spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      data-source-properties:
        sslmode: require
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.motors: INFO
    root: WARN
